name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@4
        with:
          node-version: '14'
          
      - run: npm install && npm run build --prod

      - uses: actions/setup-node@4
        with:
          node-version: '20'

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LUIZPPA_COM }}'
          channelId: live
          projectId: luizppa-com
